Repository YAPP-Github/Orbit-Android, pull requests merged in 2025-01, with the labels that each got.

#6 [SETTING/YAF-38] 디자인 시스템을 적용합니다.
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Font.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitColors.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTheme.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/pretendard_bold.ttf
  core/designsystem/src/main/res/font/pretendard_medium.ttf
  core/designsystem/src/main/res/font/pretendard_regular.ttf
  core/designsystem/src/main/res/font/pretendard_semi_bold.ttf
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
Labels: 🎨 DESIGN

#9 [FEAT/YAF-41] 알람 정보를 저장하기 위한 Room DB 를 설정합니다
  data/build.gradle.kts
  data/src/main/java/com/yapp/data/local/AlarmDao.kt
  data/src/main/java/com/yapp/data/local/AlarmDatabase.kt
  data/src/main/java/com/yapp/data/local/AlarmEntity.kt
  data/src/main/java/com/yapp/data/local/datasource/AlarmLocalDataSource.kt
  data/src/main/java/com/yapp/data/local/datasource/AlarmLocalDataSourceImpl.kt
  data/src/main/java/com/yapp/data/local/di/DataSourceModule.kt
  data/src/main/java/com/yapp/data/local/di/DatabaseModule.kt
  data/src/main/java/com/yapp/data/local/di/RepositoryModule.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  data/src/main/java/com/yapp/data/remote/datasource/DummyDataSource.kt
  data/src/main/java/com/yapp/data/remote/datasource/DummyDataSourceImpl.kt
  data/src/main/java/com/yapp/data/remote/di/DataSourceModule.kt
  data/src/main/java/com/yapp/data/remote/di/DummyRepositoryModule.kt
  data/src/main/java/com/yapp/data/remote/di/DummyServiceModule.kt
  data/src/main/java/com/yapp/data/remote/dto/request/RequestDummyDto.kt
  data/src/main/java/com/yapp/data/remote/dto/response/ResponseDummyDto.kt
  data/src/main/java/com/yapp/data/remote/repositoryimpl/DummyRepositoryImpl.kt
  data/src/main/java/com/yapp/data/remote/service/DummyService.kt
  data/src/main/java/com/yapp/data/remote/utils/ApiCallUtils.kt
  data/src/main/java/com/yapp/data/remote/utils/ApiError.kt
  domain/src/main/java/com/yapp/domain/model/Alarm.kt
  domain/src/main/java/com/yapp/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
  gradle/libs.versions.toml
Labels: ✨ FEAT

#11 [UI/YAF-54] 공통 컴포넌트를 생성합니다.
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitColors.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_check_green.xml
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/yapp/ui/component/button/OrbitButton.kt
  core/ui/src/main/java/com/yapp/ui/component/snackbar/OrbitSnackBar.kt
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/PickerState.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#13 [UI/YAF-54] 공통 컴포넌트를 생성합니다.
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/ui/src/main/java/com/yapp/ui/component/checkbox/CheckBox.kt
  core/ui/src/main/java/com/yapp/ui/component/radiobutton/RadioButton.kt
  core/ui/src/main/java/com/yapp/ui/component/switch/Switch.kt
  data/src/main/java/com/yapp/data/local/AlarmEntity.kt
  data/src/main/java/com/yapp/data/local/datasource/AlarmLocalDataSourceImpl.kt
  data/src/main/java/com/yapp/data/local/di/DataSourceModule.kt
  data/src/main/java/com/yapp/data/local/di/DatabaseModule.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/model/Alarm.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#18 [UI/YAF-59] 온보딩 알림 시간 설정 UI를 구현 합니다
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_back.xml
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  core/ui/src/main/java/com/yapp/ui/utils/ScreenPercentage.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/AndroidManifest.xml
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/consumer-rules.pro
  feature/onboarding/proguard-rules.pro
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/OnbardingTopAppBar.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/OnboardingBottomBar.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingAppState.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingDestination.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/RememberOnboardingAppState.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/Routes.kt
  feature/onboarding/src/main/res/values/values.xml
  settings.gradle.kts
Labels: 📱 UI, 👊 문수문수문수문수문수

#24 [REFACTOR/YAF-000] 디자인 시스템을 수정합니다.
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
Labels: ♻️ REFACTOR, 💪 동현동현동현동현동현

#22 [UI/YAF-66] 온보딩 생년월일 UI를 구현합니다.
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  core/ui/src/main/java/com/yapp/ui/utils/DpToPx.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingExplainScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#25 [UI/YAF-60] 온보딩 태어난 시간, 이름 입력 UI를 구현합니다.
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  core/ui/src/main/java/com/yapp/ui/utils/ScreenPercentage.kt
  feature/onboarding/src/main/java/com/kms/onboarding/BirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingDestination.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#28 [UI/YAF-30] 알람 설정 시 'Time / Hour / Minute' 을 조정하도록 한다
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeNavigation.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/BirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#30 [UI/YAF-61] 온보딩 성별 선택 UI를 구현합니다.
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
  core/ui/src/main/java/com/yapp/ui/utils/ScreenPercentage.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/OnboardingGenderToggle.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingDestination.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/Routes.kt
  feature/onboarding/src/main/res/values/values.xml
Labels: 📱 UI, 👊 문수문수문수문수문수

#32 [UI/YAF-62] 온보딩 유저정보 바텀시트를 구현합니다.
  core/ui/src/main/java/com/yapp/ui/component/OrbitBottomSheet.kt
  core/ui/src/main/java/com/yapp/ui/component/button/OrbitButton.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/UserInfoBottomSheet.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#34 [UI/YAF-68] 알람 설정 시 요일 반복 설정
  app/build.gradle.kts
  build-logic/src/main/java/com/yapp/convention/KotlinAndroid.kt
  core/designsystem/src/main/res/drawable/ic_holiday.xml
  core/ui/src/main/java/com/yapp/ui/base/BaseViewModel.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmDay.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmCheckItem.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmDayButton.kt
  feature/home/src/main/java/com/yapp/home/HomeNavigation.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/yapp/mypage/MyPageNavigation.kt
  feature/mypage/src/main/java/com/yapp/mypage/MypageScreen.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/yapp/navigator/navigation/MainNavigator.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#37 [BugFix] OrbitPickerItem 초기화 및 재구성 시 상태 동기화 문제
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/PickerState.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#38 [UI/YAF-67] 온보딩 접근권한 설정 UI를 구현합니다.
  core/designsystem/src/main/res/drawable-xhdpi/ic_onboarding_authorization_refusal.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_onboarding_authorization_refusal.png
  core/designsystem/src/main/res/drawable/ic_onboarding_authorization_guide.xml
  core/designsystem/src/main/res/drawable/ic_onboarding_authorization_refusal.png
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/UserInfoBottomSheet.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingDestination.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/Routes.kt
  feature/onboarding/src/main/res/values/values.xml
Labels: 📱 UI, 👊 문수문수문수문수문수

#44 [FEAT/YAF-000] 네비게이션 로직을 통합합니다.
  core/common/build.gradle.kts
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/common/src/main/java/com/yapp/common/navigation/Routes.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/HomeDestination.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/MyPageDestination.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/OnboardingDestination.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/TopLevelDestination.kt
  core/common/src/main/java/com/yapp/common/navigation/extensions/SharedViewModelExtensions.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeNavigation.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/yapp/mypage/MyPageNavGraph.kt
  feature/mypage/src/main/java/com/yapp/mypage/MyPageNavigation.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainBottomNavigationBar.kt
  feature/navigator/src/main/java/com/yapp/navigator/NavItem.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitBottomNavigationBar.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/navigator/src/main/java/com/yapp/navigator/navigation/MainNavigator.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen1.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingExplainScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingAppState.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingDestination.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/RememberOnboardingAppState.kt
  feature/onboarding/src/main/java/com/kms/onboarding/navigation/Routes.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#46 [UI/YAF-74] 알람 설정 시 알람 미루기를 설정할 수 있다
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/designsystem/src/main/res/drawable/ic_arrow_right.xml
  core/ui/src/main/java/com/yapp/ui/component/OrbitBottomSheet.kt
  core/ui/src/main/java/com/yapp/ui/component/radiobutton/RadioButton.kt
  core/ui/src/main/java/com/yapp/ui/component/switch/Switch.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmDay.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmCheckItem.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSnoozeBottomSheet.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/res/values/strings.xml
Labels: 📱 UI, 💪 동현동현동현동현동현

#47 [REFACTOR/YAF-000] 온보딩 UI 개선을 진행합니다.
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/onboarding/src/main/java/com/kms/onboarding/BirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen1.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingExplainScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/DebounceManager.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/OnboardingBottomBar.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#49 [UI/YAF-79] 알람 설정 시 사운드 설정을 할 수 있다
  core/designsystem/src/main/res/drawable/ic_sound_volume.xml
  core/ui/src/main/java/com/yapp/ui/component/checkbox/OrbitCheckBox.kt
  core/ui/src/main/java/com/yapp/ui/component/radiobutton/OrbitRadioButton.kt
  core/ui/src/main/java/com/yapp/ui/component/slider/OrbitSlider.kt
  core/ui/src/main/java/com/yapp/ui/component/switch/OrbitSwitch.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmDayButton.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSnoozeBottomSheet.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSoundBottomSheet.kt
  feature/home/src/main/res/values/strings.xml
Labels: 📱 UI, 💪 동현동현동현동현동현

#50 [Feat/YAP-63] 온보딩 시스템 알림권한 설정을 구현합니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/designsystem/src/main/res/drawable/ic_onboarding_shake_ten.xml
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen1.kt
  gradle/libs.versions.toml
Labels: ✨ FEAT, 👊 문수문수문수문수문수

#52 [UI/YAF-82] 미션 메인 UI를 구현합니다.
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/common/src/main/java/com/yapp/common/navigation/Routes.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/MissionDestination.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable-xhdpi/img_mission_main_background.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_mission_main_background.png
  core/designsystem/src/main/res/drawable/ic_mission_main.xml
  core/designsystem/src/main/res/drawable/img_mission_main_background.png
  feature/mission/.gitignore
  feature/mission/build.gradle.kts
  feature/mission/consumer-rules.pro
  feature/mission/proguard-rules.pro
  feature/mission/src/main/AndroidManifest.xml
  feature/mission/src/main/java/com/yapp/mission/MissionNavGraph.kt
  feature/mission/src/main/java/com/yapp/mission/MissionScreen.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitBottomNavigationBar.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnBoardingScreen.kt
  settings.gradle.kts
Labels: 📱 UI, 👊 문수문수문수문수문수

#54 [UI/YAF-85] 알람 메인 화면 배경을 구현합니다.
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_0_to_49_speech_bubble.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_50_to_79_speech_bubble.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_80_to_100_speech_bubble.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_preload_speech_bubble.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_main_no_alarm_star.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_main_sky.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_no_alarm_speech_buble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_0_to_49_speech_bubble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_50_to_79_speech_bubble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_80_to_100_speech_bubble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_preload_speech_bubble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_main_no_alarm_star.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_main_sky.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_no_alarm_speech_bubble.png
  core/designsystem/src/main/res/drawable/ic_mail.xml
  core/designsystem/src/main/res/drawable/ic_main_background.xml
  core/designsystem/src/main/res/drawable/ic_plus.xml
  core/designsystem/src/main/res/drawable/ic_setting.xml
  core/designsystem/src/main/res/raw/fortune_0_to_49.json
  core/designsystem/src/main/res/raw/fortune_50_to_79.json
  core/designsystem/src/main/res/raw/fortune_80_to_100.json
  core/designsystem/src/main/res/raw/fortune_preload.json
  core/designsystem/src/main/res/raw/step2.json
  core/designsystem/src/main/res/raw/step3.json
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/yapp/ui/component/dialog/OrbitDialog.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeNavigation.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/yapp/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  gradle/libs.versions.toml
Labels: 📱 UI, 💪 동현동현동현동현동현

#59 [UI] 알람 도착 시간 및 목록 바텀시트를 구현합니다.
  core/designsystem/src/main/res/drawable/ic_more.xml
  domain/src/main/java/com/yapp/domain/model/AlarmDay.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmDay.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmDayLabel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmListBottomSheet.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 📱 UI, 💪 동현동현동현동현동현

#62 [UI/YAF-000] 알람 설정 관련 변경사항을 수정합니다.
  app/build.gradle.kts
  core/media/.gitignore
  core/media/build.gradle.kts
  core/media/consumer-rules.pro
  core/media/proguard-rules.pro
  core/media/src/main/AndroidManifest.xml
  core/media/src/main/java/com/yapp/media/ringtone/RingtoneManagerHelper.kt
  core/media/src/main/java/com/yapp/media/sound/SoundPlayer.kt
  core/ui/src/main/java/com/yapp/ui/component/radiobutton/OrbitRadioButton.kt
  core/ui/src/main/java/com/yapp/ui/component/slider/OrbitSlider.kt
  data/build.gradle.kts
  data/src/main/java/com/yapp/data/local/di/DatabaseModule.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/model/AlarmSound.kt
  domain/src/main/java/com/yapp/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSnoozeBottomSheet.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSoundBottomSheet.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  settings.gradle.kts
Labels: ✨ FEAT, 📱 UI, 💪 동현동현동현동현동현
