Repository YAPP-Github/Orbit-Android, pull requests merged in 2025-02, with the labels that each got.

#64 [UI/YAF-000] 운세 컴포넌트 구현 및 Screen구성을 진행합니다.
  core/designsystem/src/main/java/com/yapp/designsystem/theme/Font.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
  core/designsystem/src/main/res/drawable-xhdpi/ic_100_buble.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_horoscope_background.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_letter_background.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_orbit_book.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_orbit_cane.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_orbit_clover.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_100_buble.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_horoscope_background.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_letter_background.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_orbit_book.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_orbit_cane.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_orbit_clover.png
  core/designsystem/src/main/res/drawable/ic_100_buble.png
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/drawable/ic_fortune_horoscope_background.png
  core/designsystem/src/main/res/drawable/ic_fortune_letter_background.png
  core/designsystem/src/main/res/drawable/ic_letter.xml
  core/designsystem/src/main/res/drawable/ic_letter_horoscope.xml
  core/designsystem/src/main/res/drawable/ic_orbit_book.png
  core/designsystem/src/main/res/drawable/ic_orbit_cane.png
  core/designsystem/src/main/res/drawable/ic_orbit_clover.png
  core/designsystem/src/main/res/font/ownglyph_pdf.ttf
  feature/fortune/.gitignore
  feature/fortune/build.gradle.kts
  feature/fortune/consumer-rules.pro
  feature/fortune/proguard-rules.pro
  feature/fortune/src/main/AndroidManifest.xml
  feature/fortune/src/main/java/com/yapp/fortune/FortunePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortunePager.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/Bubble.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/FortuneCharacterAnimation.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/FortuneTopAppBar.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/HillWithGradient.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/SlidingIndicator.kt
  feature/navigator/build.gradle.kts
  settings.gradle.kts
Labels: 📱 UI, 👊 문수문수문수문수문수

#67 [UI/YAF-000] 미션 진행 및 완료 UI를 구현합니다
  core/common/src/main/java/com/yapp/common/navigation/Routes.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/MissionDestination.kt
  core/designsystem/src/main/res/drawable-xhdpi/img_mission_main.png
  core/designsystem/src/main/res/drawable-xhdpi/img_mission_progress_background.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_mission_main.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_mission_progress_background.png
  core/designsystem/src/main/res/drawable/ic_amulet_back.xml
  core/designsystem/src/main/res/drawable/ic_amulet_front.xml
  core/designsystem/src/main/res/drawable/ic_cancel.xml
  core/designsystem/src/main/res/drawable/ic_mission_main.xml
  core/designsystem/src/main/res/drawable/img_mission_main.png
  core/designsystem/src/main/res/drawable/img_mission_progress_background.png
  core/designsystem/src/main/res/raw/mission_success.json
  core/ui/src/main/java/com/yapp/ui/component/dialog/OrbitDialog.kt
  feature/mission/src/main/java/com/yapp/mission/MissionContract.kt
  feature/mission/src/main/java/com/yapp/mission/MissionNavGraph.kt
  feature/mission/src/main/java/com/yapp/mission/MissionProgressScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/mission/src/main/java/com/yapp/mission/ShakeDetector.kt
  feature/mission/src/main/java/com/yapp/mission/component/FlipCard.kt
  feature/mission/src/main/java/com/yapp/mission/component/MissionProgressBar.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#68 [UI/YAF-000] 알람 설정 UI QA
  core/media/src/main/java/com/yapp/media/sound/SoundPlayer.kt
  core/ui/src/main/java/com/yapp/ui/component/OrbitBottomSheet.kt
  core/ui/src/main/java/com/yapp/ui/component/slider/OrbitSlider.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSoundBottomSheet.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#70 [FEAT] 온보딩-홈-알람 설정 네비게이션 연결
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#72 [UI/YAF-107] 알람 목록에서 선택 후 삭제가 가능해야 한다
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/designsystem/src/main/res/drawable/ic_edit.xml
  core/ui/src/main/java/com/yapp/ui/component/checkbox/OrbitCheckBox.kt
  core/ui/src/main/java/com/yapp/ui/extensions/CustomClickable.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/java/com/yapp/home/component/AlarmListDropDownMenu.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
  feature/home/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 📱 UI, 💪 동현동현동현동현동현

#74 [UI/YAF-112] 남은 운세 컴포넌트를 추가하고 페이지에 배치를 진행합니다.
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitColors.kt
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_complete_background.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_complete_background.png
  core/designsystem/src/main/res/drawable/ic__affection.xml
  core/designsystem/src/main/res/drawable/ic__graduationcap.xml
  core/designsystem/src/main/res/drawable/ic_circle.xml
  core/designsystem/src/main/res/drawable/ic_food.xml
  core/designsystem/src/main/res/drawable/ic_fortune_complete_background.png
  core/designsystem/src/main/res/drawable/ic_glove.xml
  core/designsystem/src/main/res/drawable/ic_health.xml
  core/designsystem/src/main/res/drawable/ic_pants.xml
  core/designsystem/src/main/res/drawable/ic_piggybank.xml
  core/designsystem/src/main/res/drawable/ic_shoes.xml
  core/designsystem/src/main/res/drawable/ic_top.xml
  core/designsystem/src/main/res/raw/reward_false.json
  core/designsystem/src/main/res/raw/reward_true.json
  domain/src/main/java/com/yapp/domain/model/fortune/Fortune.kt
  feature/fortune/build.gradle.kts
  feature/fortune/src/main/java/com/yapp/fortune/CodyItem.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortunePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/Bubble.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/CodyBox.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/DetailHoroScopeText.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/HillWithGradient.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/LuckyColorBox.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneCompletePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneFirstPage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePageData.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePageLayout.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePager.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/CodyContent.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/HoroscopeContent.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/LuckyColorContent.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#75 [FEAT] 추가한 알람 정보를 폰의 로컬 스토리지에 저장할 수 있어야 한다
  core/designsystem/src/main/res/raw/star_loading.json
  core/ui/src/main/java/com/yapp/ui/component/snackbar/OrbitSnackBar.kt
  core/ui/src/main/java/com/yapp/ui/utils/LazyListExtension.kt
  data/src/main/java/com/yapp/data/local/AlarmDao.kt
  data/src/main/java/com/yapp/data/local/datasource/AlarmLocalDataSource.kt
  data/src/main/java/com/yapp/data/local/datasource/AlarmLocalDataSourceImpl.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/model/Alarm.kt
  domain/src/main/java/com/yapp/domain/model/AlarmDay.kt
  domain/src/main/java/com/yapp/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/java/com/yapp/home/component/AlarmListDropDownMenu.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#84 [FEAT/YAF-113] 알람 아이템을 클릭하여 수정할 수 있다
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/common/src/main/java/com/yapp/common/util/ResourceProvider.kt
  core/designsystem/src/main/res/drawable/ic_alert.xml
  core/media/src/main/java/com/yapp/media/sound/SoundPlayer.kt
  core/ui/src/main/java/com/yapp/ui/component/snackbar/OrbitSnackBar.kt
  data/src/main/java/com/yapp/data/local/repositoryimpl/AlarmRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/model/Alarm.kt
  domain/src/main/java/com/yapp/domain/model/AlarmDay.kt
  domain/src/main/java/com/yapp/domain/repository/AlarmRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/AlarmUseCase.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
  feature/home/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#86 [FEAT/YAF-000] 알람 기능 2차 UT QA
  core/common/build.gradle.kts
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/common/src/main/java/com/yapp/common/navigation/extensions/SharedViewModelExtensions.kt
  core/common/src/main/java/com/yapp/common/util/ResourceProvider.kt
  core/designsystem/src/main/res/drawable-xhdpi/ic_main_sky.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_main_sky.png
  feature/fortune/src/main/java/com/yapp/fortune/FortuneNavGraph.kt
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/mission/src/main/java/com/yapp/mission/MissionNavGraph.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#87 [REFACTOR] 2차 UT 온보딩 QA
  core/designsystem/src/main/res/raw/step2.json
  core/designsystem/src/main/res/raw/step3.json
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingBirthdayScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen1.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/component/OnboardingBottomBar.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#91 [REFACTOR] 2차 UT 운세 QA를 반영합니다.
  .editorconfig
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/designsystem/src/main/res/drawable/ic_letter.xml
  feature/fortune/src/main/java/com/yapp/fortune/CodyItem.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortunePagesProvider.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneRewardScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/Bubble.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/CodyBox.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/DetailHoroScopeText.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneCompletePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneFirstPage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePager.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/CodyContent.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/LuckyColorContent.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#93 [FEAT/YAF-000] 사용자 경험 향상을 위한 햅틱 피드백 추가
  app/src/main/AndroidManifest.xml
  core/media/src/main/java/com/yapp/media/haptic/HapticFeedbackManager.kt
  core/ui/build.gradle.kts
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/alarm/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/mission/build.gradle.kts
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#96 [FEAT] 활성화된 알람이 없을 시 다이얼로그를 노출하고 화면 문구를 변경한다
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#98 [BUGFIX] 타임피커 오류 해결 및 UX라이팅 수정
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortunePagesProvider.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneFirstPage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/LuckyColorContent.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
Labels: 🛠️ FIX, 👊 문수문수문수문수문수

#100 [UI/YAF-117] 설정 UI Component를 구현합니다.
  core/designsystem/src/main/res/drawable/ic_orbit_write_fortune.xml
  feature/mypage/src/main/java/com/yapp/mypage/MyPageNavGraph.kt
  feature/mypage/src/main/java/com/yapp/mypage/MypageScreen.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/setting/.gitignore
  feature/setting/build.gradle.kts
  feature/setting/consumer-rules.pro
  feature/setting/proguard-rules.pro
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/component/InquiryCard.kt
  feature/setting/src/main/java/com/yapp/setting/component/SettingItem.kt
  feature/setting/src/main/java/com/yapp/setting/component/SettingTopAppBar.kt
  feature/setting/src/main/java/com/yapp/setting/component/TableOfContentsText.kt
  feature/setting/src/main/java/com/yapp/setting/component/UserInfoCard.kt
  feature/setting/src/main/java/com/yapp/setting/component/VersionCodeText.kt
  settings.gradle.kts
Labels: 📱 UI, 👊 문수문수문수문수문수

#102 [FEAT/YAF-116] 알림이 울릴 때 해제 혹은 미루기가 가능한 UI를 표시한다
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/common/src/main/java/com/yapp/common/navigation/Routes.kt
  core/common/src/main/java/com/yapp/common/navigation/destination/HomeDestination.kt
  core/designsystem/src/main/res/drawable/ic_alarm_action_character.xml
  feature/home/src/main/java/com/yapp/alarm/action/AlarmActionContract.kt
  feature/home/src/main/java/com/yapp/alarm/action/AlarmActionScreen.kt
  feature/home/src/main/java/com/yapp/alarm/action/AlarmActionViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/snooze/AlarmSnoozeTimerContract.kt
  feature/home/src/main/java/com/yapp/alarm/snooze/AlarmSnoozeTimerScreen.kt
  feature/home/src/main/java/com/yapp/alarm/snooze/AlarmSnoozeTimerViewModel.kt
  feature/home/src/main/java/com/yapp/home/HomeNavGraph.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
Labels: 📱 UI, 💪 동현동현동현동현동현

#104 [UI/YAF-000] 알람 미루기 타이머 버튼 위치 수정 및 화면 연결
  app/build.gradle.kts
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  feature/home/src/main/java/com/yapp/alarm/action/AlarmActionContract.kt
  feature/home/src/main/java/com/yapp/alarm/action/AlarmActionViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/snooze/AlarmSnoozeTimerScreen.kt
  feature/home/src/main/java/com/yapp/alarm/snooze/AlarmSnoozeTimerViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#106 [UI/YAF-000] 세팅 UI Component를 연결합니다.
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/component/InquiryCard.kt
  feature/setting/src/main/java/com/yapp/setting/component/SettingItem.kt
  feature/setting/src/main/java/com/yapp/setting/component/TableOfContentsText.kt
  feature/setting/src/main/java/com/yapp/setting/component/UserInfoCard.kt
  feature/setting/src/main/java/com/yapp/setting/component/VersionCodeText.kt
Labels: 📱 UI, 👊 문수문수문수문수문수

#112 [FEAT/YAF-000] 사용자 등록/조회 연결을 진행합니다.
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  core/datastore/src/main/java/com/yapp/datastore/UserPreferences.kt
  core/datastore/src/main/java/com/yapp/datastore/di/DataStoreModule.kt
  core/network/src/main/java/com/yapp/network/di/NetworkModule.kt
  data/build.gradle.kts
  data/src/main/java/com/yapp/data/remote/datasource/SignUpDataSource.kt
  data/src/main/java/com/yapp/data/remote/datasource/SignUpDataSourceImpl.kt
  data/src/main/java/com/yapp/data/remote/datasource/UserInfoDataSource.kt
  data/src/main/java/com/yapp/data/remote/datasource/UserInfoDataSourceImpl.kt
  data/src/main/java/com/yapp/data/remote/di/DataSourceModule.kt
  data/src/main/java/com/yapp/data/remote/di/DummyRepositoryModule.kt
  data/src/main/java/com/yapp/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/yapp/data/remote/di/ServiceModule.kt
  data/src/main/java/com/yapp/data/remote/dto/request/SignUpRequest.kt
  data/src/main/java/com/yapp/data/remote/dto/response/UserResponse.kt
  data/src/main/java/com/yapp/data/remote/repositoryimpl/SignUpRepositoryImpl.kt
  data/src/main/java/com/yapp/data/remote/repositoryimpl/UserInfoRepositoryImpl.kt
  data/src/main/java/com/yapp/data/remote/service/ApiService.kt
  data/src/main/java/com/yapp/data/remote/utils/ApiCallUtils.kt
  domain/src/main/java/com/yapp/domain/model/User.kt
  domain/src/main/java/com/yapp/domain/repository/SignUpRepository.kt
  domain/src/main/java/com/yapp/domain/repository/UserInfoRepository.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainContract.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainViewModel.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/navigator/src/main/java/com/yapp/navigator/SplashScreen.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/yapp/setting/EditProfileScreen.kt
  feature/setting/src/main/java/com/yapp/setting/SettingContract.kt
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/SettingViewModel.kt
Labels: ✨ FEAT, 👊 문수문수문수문수문수

#116 [FEAT] 알람 해제 UX 개선 및 알람 권한 요청
  core/alarm/src/main/java/com/yapp/alarm/pendingIntent/interaction/AlarmAlertPendingIntent.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
  core/ui/src/main/java/com/yapp/ui/lifecycle/LaunchedEffectWithLifecycle.kt
  feature/alarm-interaction/src/main/java/com/yapp/alarm/interaction/AlarmInteractionActivity.kt
  feature/alarm-interaction/src/main/java/com/yapp/alarm/interaction/action/AlarmActionScreen.kt
  feature/alarm-interaction/src/main/java/com/yapp/alarm/interaction/snooze/AlarmSnoozeTimerScreen.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
  feature/splash/src/main/java/com/yapp/splash/SplashScreen.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#119 [FEAT] 알람 해제 후 미션 화면 연결
  app/src/main/AndroidManifest.xml
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmInteractionActivityReceiver.kt
  feature/mission/src/main/java/com/yapp/mission/MissionNavGraph.kt
  feature/navigator/src/main/java/com/yapp/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#121 [FEAT] 알람 설정 화면 QA 수정
  core/ui/src/main/java/com/yapp/ui/component/dialog/OrbitDialog.kt
  core/ui/src/main/java/com/yapp/ui/component/snackbar/OrbitSnackBar.kt
  core/ui/src/main/java/com/yapp/ui/component/switch/OrbitSwitch.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditContract.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmDayButton.kt
  feature/home/src/main/java/com/yapp/alarm/component/bottomsheet/AlarmSnoozeBottomSheet.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#123 [FEAT] 홈 화면 QA 수정
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
  feature/home/src/main/res/values/strings.xml
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#118 [FEAT/YAF-000] 운세 생성/조회 연결을 진행합니다.
  core/datastore/src/main/java/com/yapp/datastore/UserPreferences.kt
  core/designsystem/src/main/java/com/yapp/designsystem/theme/OrbitTypography.kt
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_reward1.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_reward2.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_reward3.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_reward4.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_fortune_reward5.png
  core/designsystem/src/main/res/drawable-xhdpi/ic_shadow.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_reward1.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_reward3.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_reward4.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_fortune_reward5.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_shadow.png
  core/designsystem/src/main/res/drawable/ic_fortune_reward1.png
  core/designsystem/src/main/res/drawable/ic_fortune_reward2.png
  core/designsystem/src/main/res/drawable/ic_fortune_reward3.png
  core/designsystem/src/main/res/drawable/ic_fortune_reward4.png
  core/designsystem/src/main/res/drawable/ic_fortune_reward5.png
  core/designsystem/src/main/res/drawable/ic_inverted_triangle.xml
  core/designsystem/src/main/res/drawable/ic_shadow.png
  core/network/src/main/java/com/yapp/network/di/NetworkModule.kt
  data/src/main/java/com/yapp/data/remote/datasource/FortuneDataSource.kt
  data/src/main/java/com/yapp/data/remote/datasource/FortuneDataSourceImpl.kt
  data/src/main/java/com/yapp/data/remote/di/DataSourceModule.kt
  data/src/main/java/com/yapp/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/yapp/data/remote/dto/response/FortuneResponse.kt
  data/src/main/java/com/yapp/data/remote/repositoryimpl/FortuneRepositoryImpl.kt
  data/src/main/java/com/yapp/data/remote/service/ApiService.kt
  data/src/main/java/com/yapp/data/remote/utils/ApiCallUtils.kt
  domain/src/main/java/com/yapp/domain/model/fortune/Fortune.kt
  domain/src/main/java/com/yapp/domain/repository/FortuneRepository.kt
  feature/fortune/build.gradle.kts
  feature/fortune/src/main/java/com/yapp/fortune/CodyItem.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneContract.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortunePagesProvider.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneRewardScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneViewModel.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/DetailHoroScopeText.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/SpeechBubble.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneFirstPage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePageData.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePageLayout.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePager.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/CodyContent.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/HoroscopeContent.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/LuckyColorContent.kt
  feature/mission/build.gradle.kts
  feature/mission/src/main/java/com/yapp/mission/MissionContract.kt
  feature/mission/src/main/java/com/yapp/mission/MissionProgressScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/mission/src/main/java/com/yapp/mission/ShakeDetector.kt
  feature/mission/src/main/java/com/yapp/mission/component/FlipCard.kt
Labels: ✨ FEAT, 👊 문수문수문수문수문수

#126 [FEAT] 알람 해제 후 미션 이동 로직 분기 처리 및 QA 수정
  core/alarm/build.gradle.kts
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmInteractionActivityReceiver.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
  core/designsystem/src/main/res/drawable/ic_amulet_front.xml
  feature/mission/src/main/java/com/yapp/mission/MissionContract.kt
  feature/mission/src/main/java/com/yapp/mission/MissionProgressScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/mission/src/main/java/com/yapp/mission/ShakeDetector.kt
  feature/mission/src/main/java/com/yapp/mission/component/FlipCard.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#132 [FEAT] 홈 화면에서 당일에 받은 운세를 확인할 수 있다.
  feature/alarm-interaction/src/main/java/com/yapp/alarm/interaction/action/AlarmActionScreen.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/res/values/strings.xml
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#134 [BugFix] 온보딩 권한 요청 수정
  feature/onboarding/src/main/java/com/kms/onboarding/OnboardingAccessScreen.kt
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#138 [REFACTOR] 세팅 웹뷰 연결을 수행합니다.
  feature/setting/src/main/java/com/yapp/setting/SettingContract.kt
  feature/setting/src/main/java/com/yapp/setting/SettingNavGraph.kt
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/yapp/setting/component/InquiryCard.kt
  feature/webview/src/main/java/com/yapp/webview/OrbitWebView.kt
  feature/webview/src/main/java/com/yapp/webview/WebViewRoute.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#139 [BugFix] 알림 미루기 후 다시 알림이 울릴 때 미션 화면으로 이동하는 문제 해결
  core/alarm/src/main/java/com/yapp/alarm/AlarmConstants.kt
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmInteractionActivityReceiver.kt
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmReceiver.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
  core/network/src/main/java/com/yapp/network/di/NetworkModule.kt
  core/ui/src/main/java/com/yapp/ui/component/snackbar/OrbitSnackBar.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneContract.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneNavGraph.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneViewModel.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingAccessScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingAlarmTimeSelectionScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingBirthdayScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingCompleteScreen1.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingCompleteScreen2.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingExplainScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingNavGraph.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/DebounceManager.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/GifImage.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/OnbardingTopAppBar.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/OnboardingBottomBar.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/UserInfoBottomSheet.kt
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#149 [BUGFIX] 푸시 알람 “알람 해제” 버튼 클릭 시 미션 화면으로 이동되지 않는 문제 해결
  build-logic/src/main/java/com/yapp/convention/Extension.kt
  core/alarm/src/main/java/com/yapp/alarm/pendingIntent/interaction/AlarmDismissPendingIntent.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
  core/common/src/main/java/com/yapp/common/navigation/OrbitNavigator.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/mission/build.gradle.kts
  feature/mission/src/main/java/com/yapp/mission/MissionNavGraph.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/navigator/src/main/java/com/yapp/navigator/OrbitNavHost.kt
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#151 [BUGFIX] 반복알림 설정 오류를 해결한다.
  core/alarm/src/main/java/com/yapp/alarm/AlarmConstants.kt
  core/alarm/src/main/java/com/yapp/alarm/AlarmHelper.kt
  core/alarm/src/main/java/com/yapp/alarm/pendingIntent/schedule/ScheduleAlarmPendingIntent.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
  domain/src/main/java/com/yapp/domain/model/AlarmDay.kt
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#153 [FEAT] 최근 운세 점수에 따라 홈화면의 캐릭터와 문구가 변합니다.
  core/datastore/src/main/java/com/yapp/datastore/UserPreferences.kt
  core/designsystem/src/main/res/drawable/ic_charcter_no_alarm.xml
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#157 [BUGFIX] Github Action CI 를 수정합니다. (Cache v4 업데이트)
  .github/workflows/android_ci.yml
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#155 [UI] 알람 설정 화면 QA 피드백 반영 및 수정
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitPickerItem.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/java/com/yapp/home/component/AlarmListDropDownMenu.kt
Labels: 🛠️ FIX, 📱 UI, 💪 동현동현동현동현동현

#168 [BUGFIX] 스와이프로 알람 삭제 시 알람 해제 불가능 현상을 해결한다. #165
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmReceiver.kt
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
Labels: 🛠️ FIX, 💪 동현동현동현동현동현

#169 [REFACTOR] 닉네임 정규표현식을 수정하고 피커 오류를 해결합니다.
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/PickerState.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingGenderScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingNameScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/res/values/values.xml
Labels: 👊 문수문수문수문수문수

#171 [FEAT] 운세 보상에 대한 분기처리를 진행합니다.
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmReceiver.kt
  core/datastore/src/main/java/com/yapp/datastore/UserPreferences.kt
  feature/alarm-interaction/build.gradle.kts
  feature/fortune/src/main/java/com/yapp/fortune/FortuneScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneViewModel.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortuneCompletePage.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/FortunePager.kt
Labels: 👊 문수문수문수문수문수

#173 [REFACTOR] 운세 v0.0.3 QA를 진행합니다.
  feature/fortune/src/main/java/com/yapp/fortune/FortuneRewardScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/FortuneScreen.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/CodyBox.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/DetailHoroScopeText.kt
  feature/fortune/src/main/java/com/yapp/fortune/page/content/CodyContent.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#175 [REFACTOR] 미션 페이지에서 카드 클릭 이벤트를 제거합니다.
  feature/mission/src/main/java/com/yapp/mission/MissionContract.kt
  feature/mission/src/main/java/com/yapp/mission/MissionProgressScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  feature/mission/src/main/java/com/yapp/mission/component/FlipCard.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#179 [BUGFIX] 온보딩 완료 시 온보딩 스택 제거 후 이동
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingViewModel.kt
Labels: 🛠️ FIX, 👊 문수문수문수문수문수

#183 [UI] 자잘한 UI 수정 및 개선
  core/designsystem/src/main/res/drawable/ic_character_no_alarm.xml
  core/designsystem/src/main/res/drawable/ic_charcter_no_alarm.xml
  core/designsystem/src/main/res/raw/fortune_preload.json
  core/ui/src/main/java/com/yapp/ui/component/OrbitBottomSheet.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
Labels: 📱 UI, 💪 동현동현동현동현동현
