Repository YAPP-Github/Orbit-Android, pull requests merged in 2025-03, with the labels that each got.

#187 [FEAT] 알람 아이템 삭제 동작을 다양화합니다.
  core/designsystem/src/main/res/drawable/ic_trash.xml
  core/ui/src/main/java/com/yapp/ui/component/button/OrbitButton.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditScreen.kt
  feature/home/src/main/java/com/yapp/alarm/addedit/AlarmAddEditViewModel.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmListItem.kt
  feature/home/src/main/java/com/yapp/home/HomeContract.kt
  feature/home/src/main/java/com/yapp/home/HomeScreen.kt
  feature/home/src/main/java/com/yapp/home/HomeViewModel.kt
  feature/home/src/main/java/com/yapp/home/component/bottomsheet/AlarmListBottomSheet.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingNavGraph.kt
  feature/setting/src/main/java/com/yapp/setting/SettingNavGraph.kt
  feature/splash/src/main/java/com/yapp/splash/SplashScreen.kt
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#193 [REFACTOR] AlarmService 내의 Handler를 CoroutineScope로 대체합니다
  core/alarm/src/main/java/com/yapp/alarm/services/AlarmService.kt
Labels: ♻️ REFACTOR, 💪 동현동현동현동현동현

#186 [REFACTOR] 1.0.0 릴리즈 버전 QA를 진행합니다.
  core/ui/src/main/java/com/yapp/ui/component/textfield/OrbitTextField.kt
  core/ui/src/main/java/com/yapp/ui/component/timepicker/OrbitYearMonthPicker.kt
  core/ui/src/main/java/com/yapp/ui/toggle/OrbitGenderToggle.kt
  feature/fortune/src/main/java/com/yapp/fortune/component/SpeechBubble.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingContract.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/OnboardingTimeOfBirthScreen.kt
  feature/onboarding/src/main/java/com/yapp/onboarding/component/UnknownBirthTimeButton.kt
  feature/onboarding/src/main/res/values/values.xml
  feature/setting/src/main/java/com/yapp/setting/EditBirthdayScreen.kt
  feature/setting/src/main/java/com/yapp/setting/EditProfileScreen.kt
  feature/setting/src/main/java/com/yapp/setting/EditProfileViewModel.kt
  feature/setting/src/main/java/com/yapp/setting/SettingContract.kt
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/SettingViewModel.kt
  feature/setting/src/main/java/com/yapp/setting/component/UserInfoCard.kt
Labels: ♻️ REFACTOR, 👊 문수문수문수문수문수

#194 [FEAT] 공휴일 알람 끄기 기능을 구현합니다.
  core/alarm/src/main/java/com/yapp/alarm/AlarmConstants.kt
  core/alarm/src/main/java/com/yapp/alarm/AlarmHelper.kt
  core/alarm/src/main/java/com/yapp/alarm/receivers/AlarmReceiver.kt
  feature/setting/src/main/java/com/yapp/setting/SettingContract.kt
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/SettingViewModel.kt
Labels: ✨ FEAT, 🛠️ FIX, 💪 동현동현동현동현동현

#200 [FEAT] 터치 미션을 구현합니다.
  core/designsystem/src/main/res/drawable-xhdpi/ic_mission_main_letter.png
  core/designsystem/src/main/res/drawable-xxhdpi/ic_mission_main_letter.png
  core/designsystem/src/main/res/drawable/ic_mission_main_letter.png
  core/designsystem/src/main/res/raw/mission_letter_open.json
  core/designsystem/src/main/res/raw/mission_letter_tap.json
  core/remoteconfig/.gitignore
  core/remoteconfig/build.gradle.kts
  core/remoteconfig/consumer-rules.pro
  core/remoteconfig/proguard-rules.pro
  core/remoteconfig/src/main/AndroidManifest.xml
  core/remoteconfig/src/main/java/com/yapp/remoteconfig/FirebaseRemoteConfigManager.kt
  core/remoteconfig/src/main/java/com/yapp/remoteconfig/di/RemoteConfigModule.kt
  core/ui/src/main/java/com/yapp/ui/component/lottie/LottieAnimation.kt
  data/build.gradle.kts
  data/src/main/java/com/yapp/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/yapp/data/remote/repositoryimpl/RemoteConfigRepositoryImpl.kt
  domain/src/main/java/com/yapp/domain/model/MissionType.kt
  domain/src/main/java/com/yapp/domain/repository/RemoteConfigRepository.kt
  domain/src/main/java/com/yapp/domain/usecase/GetMissionTypeUseCase.kt
  feature/mission/src/main/java/com/yapp/mission/MissionContract.kt
  feature/mission/src/main/java/com/yapp/mission/MissionProgressScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionScreen.kt
  feature/mission/src/main/java/com/yapp/mission/MissionViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ FEAT, 👊 문수문수문수문수문수

#201 [UI] ic_check 에셋 교체
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/drawable/ic_check_border_lined.xml
  core/designsystem/src/main/res/drawable/ic_filter.xml
  core/ui/src/main/java/com/yapp/ui/component/checkbox/OrbitCheckBox.kt
  feature/home/src/main/java/com/yapp/alarm/component/AlarmCheckItem.kt
Labels: 📱 UI, 💪 동현동현동현동현동현

#203 [FEAT] Firebase Analytics 연동
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ FEAT, 💪 동현동현동현동현동현

#206 [REFACTOR] versionName을 하드코딩된 값에서 동적으로 가져오는 방식으로 변경
  feature/setting/src/main/java/com/yapp/setting/SettingScreen.kt
  feature/setting/src/main/java/com/yapp/setting/component/VersionCodeText.kt
Labels: ♻️ REFACTOR, 💪 동현동현동현동현동현

#209 [Docs] README 업데이트
  README.md
  project.dot.png
Labels: 💪 동현동현동현동현동현, 📄 DOCS
